# Generated by Django 4.2.1 on 2023-06-21 21:04

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=40)),
                ('tag', models.CharField(max_length=20, null=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('courier', 'courier'), ('sender', 'sender'), ('drop_pick_zone', 'drop_pick_zone'), ('warehouse', 'warehouse')], max_length=20, verbose_name='role')),
                ('status', models.CharField(choices=[('available', 'Available'), ('on-trip', 'On Trip')], default='available', max_length=20)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('warehouse', models.CharField(max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(max_length=100)),
                ('deliveryType', models.CharField(choices=[('standard', 'standard'), ('premium', 'premium'), ('express', 'express')], max_length=20)),
                ('packageDescription', models.TextField()),
                ('recipientName', models.CharField(max_length=100)),
                ('recipientEmail', models.CharField(max_length=100)),
                ('recipientTelephone', models.CharField(max_length=100)),
                ('recipientAddress', models.CharField(max_length=200)),
                ('sendersAddress', models.CharField(max_length=200)),
                ('package_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('upcoming', 'upcoming'), ('dropped_off', 'dropped Off'), ('dispatched', 'dispatched'), ('en_route', 'en_route'), ('warehouse_arrival', 'warehouse_arrival'), ('in_house', 'in house'), ('ready_for_pickup', 'ready_for_pickup'), ('in_transit', 'in transit'), ('at_pickup', 'at pickup'), ('pending_delivery', 'pending delivery'), ('out_for_delivery', 'out for delivery'), ('ongoing', 'ongoing'), ('arrived', 'arrived'), ('completed', 'completed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_packages', to=settings.AUTH_USER_MODEL)),
                ('dropOffLocation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages_dropped_off', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
