# Generated by Django 4.2.1 on 2023-08-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='genderType',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='package',
            name='sendersEmail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='sendersName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
