# Generated by Django 4.2.1 on 2023-06-24 11:44

from django.db import migrations
import lmsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', lmsapp.models.CustomUserManager()),
            ],
        ),
    ]
