# Generated by Django 4.2.1 on 2023-08-18 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_alter_package_user_alter_user_email'),
        ('lmsapp', '0003_alter_package_user_apikey'),
    ]

    operations = [
    ]
