# Generated by Django 4.2.1 on 2023-06-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_package_warehouse_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('upcoming', 'upcoming'), ('dropped_off', 'dropped Off'), ('dispatched', 'dispatched'), ('en_route', 'en_route'), ('warehouse_arrival', 'warehouse_arrival'), ('in_house', 'in house'), ('in_transit', 'in transit'), ('ready_for_pickup', 'ready_for_pickup'), ('at_pickup', 'at pickup'), ('pending_delivery', 'pending delivery'), ('out_for_delivery', 'out for delivery'), ('ongoing', 'ongoing'), ('arrived', 'arrived'), ('completed', 'completed')], max_length=20),
        ),
    ]
