# Generated by Django 4.2.1 on 2023-08-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0004_merge_20230818_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='recipientIdentification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
