# Generated by Django 4.2.1 on 2023-07-04 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0005_alter_package_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='package',
            name='otp',
        ),
        migrations.AlterField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='package',
            name='deliveryType',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('express', 'Express')], max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('dropped_off', 'Dropped Off'), ('dispatched', 'Dispatched'), ('en_route', 'En Route'), ('warehouse_arrival', 'Warehouse Arrival'), ('in_house', 'In House'), ('in_transit', 'In Transit'), ('at_pickup', 'At Pickup'), ('ready_for_pickup', 'Ready for Pickup'), ('pending_delivery', 'Pending Delivery'), ('out_for_delivery', 'Out for Delivery'), ('ongoing', 'Ongoing'), ('arrived', 'Arrived'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('courier', 'Courier'), ('sender', 'Sender'), ('drop_pick_zone', 'Drop/Pick Zone'), ('warehouse', 'Warehouse')], max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drop_pick_zones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DropPickZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_pick_zones', to='lmsapp.warehouse')),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='dropOffLocation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages_dropped_off', to='lmsapp.droppickzone'),
        ),
        migrations.AlterField(
            model_name='package',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages_in_house', to='lmsapp.warehouse'),
        ),
    ]
