# Generated by Django 4.2.1 on 2023-08-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0005_alter_package_recipientidentification'),
    ]

    operations = [
        migrations.AddField(
            model_name='droppickzone',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
