# Generated by Django 4.2.1 on 2023-08-23 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0005_alter_package_recipientidentification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoogleSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sheet_url', models.URLField(blank=True, null=True, unique=True)),
                ('header_mapping', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
