# Generated by Django 4.2.1 on 2023-08-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0006_droppickzone_email_warehouse_email'),
        ('lmsapp', '0006_usergooglesheet'),
    ]

    operations = [
    ]
