# Generated by Django 4.2.1 on 2023-07-05 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0006_warehouse_remove_package_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
