# Generated by Django 4.2.1 on 2023-07-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0007_package_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DropPickZone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
