# Generated by Django 4.2.1 on 2023-07-05 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0008_user_droppickzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DropPickZone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to=settings.AUTH_USER_MODEL),
        ),
    ]
