# Generated by Django 4.2.1 on 2023-07-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0009_alter_user_droppickzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='droppickzone',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='droppickzone',
            name='address',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='droppickzone',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
