# Generated by Django 4.2.1 on 2023-09-04 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0010_remove_droppickzone_email_remove_warehouse_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='lmsapp.warehouse'),
        ),
    ]
