# Generated by Django 4.2.1 on 2023-07-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0010_droppickzone_tag_warehouse_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
