# Generated by Django 4.2.1 on 2023-07-05 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0012_droppickzone_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='lmsapp.warehouse'),
        ),
    ]
