# Generated by Django 4.2.1 on 2023-09-12 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0012_alter_droppickzone_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tag',
        ),
        migrations.AlterField(
            model_name='package',
            name='dropOffLocation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropped_off_at', to='lmsapp.droppickzone'),
        ),
    ]
