# Generated by Django 4.2.1 on 2023-07-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0014_alter_user_droppickzone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='DropPickZone',
            new_name='drop_pick_zone',
        ),
    ]
