# Generated by Django 4.2.1 on 2023-09-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0014_courierlocationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_changed_password',
            field=models.BooleanField(default=False),
        ),
    ]
