# Generated by Django 4.2.1 on 2023-09-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0015_user_has_changed_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_changed_password',
            new_name='has_set_password',
        ),
    ]
