# Generated by Django 4.2.1 on 2023-07-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0015_rename_droppickzone_user_drop_pick_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
