# Generated by Django 4.2.1 on 2023-07-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0016_package_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
