# Generated by Django 4.2.1 on 2023-07-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0017_warehouse_latitude_warehouse_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='droppickzone',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='droppickzone',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
