# Generated by Django 4.2.1 on 2023-07-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0019_package_sender_latitude_package_sender_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='recipient_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='recipient_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
