# Generated by Django 4.2.1 on 2023-07-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0023_alter_user_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pickupPoint',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages_picked_up', to='lmsapp.droppickzone'),
        ),
    ]
