# Generated by Django 4.2.1 on 2023-07-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0026_rename_pickuplocation_package_recipientpickuplocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='genderType',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='recipientIdentification',
            field=models.CharField(default=1234567, max_length=200),
            preserve_default=False,
        ),
    ]
