# Generated by Django 4.2.1 on 2023-07-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0029_alter_package_gendertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='sendersContact',
            field=models.CharField(default=1234567, max_length=200),
            preserve_default=False,
        ),
    ]
