# Generated by Django 4.2.1 on 2023-07-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0032_package_delivery_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='delivery_fee',
            new_name='deliveryFee',
        ),
    ]
