# Generated by Django 4.2.1 on 2023-07-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0034_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
