# Generated by Django 4.2.1 on 2023-08-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0036_package_sendersemail_package_sendersname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='genderType',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='package',
            name='sendersAddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
