# Generated by Django 4.2.1 on 2023-08-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0037_alter_package_gendertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='deliveryFee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='dropOffLocation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='genderType',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=123456, max_length=20, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='recipientPickUpLocation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
