# Generated by Django 4.2.1 on 2023-08-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0040_alter_package_dropofflocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='dropOffLocation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='recipientPickUpLocation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
