# Generated by Django 4.2.1 on 2023-08-09 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0041_alter_package_dropofflocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='dropOffLocation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages_dropped_off', to='lmsapp.droppickzone'),
        ),
        migrations.AlterField(
            model_name='package',
            name='recipientPickUpLocation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages_picked_up', to='lmsapp.droppickzone'),
        ),
    ]
