# Generated by Django 4.2.1 on 2023-05-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_is_courrier_remove_user_is_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('courier', 'courier'), ('sender', 'sender'), ('recipient', 'recipient')], default='sender', max_length=10, verbose_name='role'),
        ),
    ]
