# Generated by Django 4.2.1 on 2023-05-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_recipient',
            field=models.BooleanField(default=False),
        ),
    ]
