# Generated by Django 4.2.1 on 2023-06-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(max_length=100)),
                ('packageDescripton', models.TextField()),
                ('recipientName', models.CharField(max_length=100)),
                ('recipientAddress', models.CharField(max_length=200)),
                ('sendersAddress', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=20)),
            ],
        ),
    ]
