# Generated by Django 4.2.1 on 2023-06-01 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
