# Generated by Django 4.2.1 on 2023-06-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_is_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_recipient',
        ),
    ]
