# Generated by Django 4.2.1 on 2023-06-01 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_package_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='packageDescripton',
            new_name='packageDescription',
        ),
        migrations.RemoveField(
            model_name='package',
            name='user_id',
        ),
        migrations.AddField(
            model_name='package',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
