# Generated by Django 4.2.1 on 2023-06-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_package_delivery_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='delivery_number',
        ),
    ]
