# Generated by Django 4.2.1 on 2023-06-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_package_delivery_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='packageDescripton',
            new_name='packageDescription',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('courier', 'courier'), ('sender', 'sender'), ('recipient', 'recipient')], max_length=10, verbose_name='role'),
        ),
    ]
