# Generated by Django 4.2.1 on 2023-06-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_packagedescripton_package_packagedescription_and_more'),
        ('account', '0009_package_delivery_number'),
    ]

    operations = [
    ]
