# Generated by Django 4.2.1 on 2023-06-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1234567, max_length=20),
            preserve_default=False,
        ),
    ]
