# Generated by Django 4.2.1 on 2023-06-06 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_package_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
