# Generated by Django 4.2.1 on 2023-06-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_package_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('on-trip', 'On Trip')], default='available', max_length=20),
        ),
    ]
