<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-06-06 12:01
=======
# Generated by Django 4.2.1 on 2023-06-06 11:38
>>>>>>> f854573e5f29a372c1e0be28fbd9d83ae4750c93

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_package_assigned_at'),
        ('account', '0014_user_status'),
    ]

    operations = [
    ]
