# Generated by Django 4.2.1 on 2023-06-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_package_assigned_at'),
        ('account', '0014_user_status'),
    ]

    operations = [
    ]
