# Generated by Django 4.2.1 on 2023-06-07 08:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_merge_0014_package_assigned_at_0014_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimePIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.package')),
            ],
        ),
    ]
