# Generated by Django 4.2.1 on 2023-06-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_merge_0014_package_assigned_at_0014_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='recipientEmail',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
    ]
