# Generated by Django 4.2.1 on 2023-06-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_onetimepin'),
        ('account', '0016_package_recipientemail'),
    ]

    operations = [
    ]
