# Generated by Django 4.2.1 on 2023-06-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_merge_0016_onetimepin_0016_package_recipientemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('arrived', 'arrived'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.DeleteModel(
            name='OneTimePIN',
        ),
    ]
