# Generated by Django 4.2.1 on 2023-06-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_package_status_delete_onetimepin'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
