# Generated by Django 4.2.1 on 2023-06-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_package_created_at_alter_package_assigned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('upcoming', 'upcoming'), ('ongoing', 'ongoing'), ('arrived', 'arrived'), ('completed', 'completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('courier', 'courier'), ('sender', 'sender')], max_length=10, verbose_name='role'),
        ),
    ]
