# Generated by Django 4.2.1 on 2023-06-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_package_status_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='recipientTelephone',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
    ]
