# Generated by Django 4.2.1 on 2023-06-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_package_recipienttelephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='deliveryType',
            field=models.CharField(choices=[('standard', 'standard'), ('premium', 'premium'), ('express', 'express')], default=123456, max_length=20),
            preserve_default=False,
        ),
    ]
