# Generated by Django 4.2.1 on 2023-06-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_package_deliverytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('courier', 'courier'), ('sender', 'sender'), ('drop_pick_zone', 'drop_pick_zone')], max_length=20, verbose_name='role'),
        ),
    ]
