# Generated by Django 4.2.1 on 2023-06-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropOffPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_off_station_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='drop_off_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.dropoffpoint'),
        ),
    ]
