# Generated by Django 4.2.1 on 2023-06-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_dropoffpoint_package_drop_off_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropOffZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='drop_off_zone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.dropoffzone'),
        ),
        migrations.AlterField(
            model_name='package',
            name='drop_off_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.dropoffzone'),
        ),
        migrations.DeleteModel(
            name='DropOffPoint',
        ),
    ]
