# Generated by Django 4.2.1 on 2023-06-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_package_dropofflocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='dropOffLocation',
        ),
    ]
