# Generated by Django 4.2.1 on 2023-06-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_remove_package_dropofflocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='dropOffLocation',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
    ]
