# Generated by Django 4.2.1 on 2023-06-13 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_dropoffzone_user_drop_off_zone_and_more'),
        ('account', '0028_alter_package_dropofflocation'),
    ]

    operations = [
    ]
