# Generated by Django 4.2.1 on 2023-06-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_alter_package_dropofflocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='delivery_number',
            new_name='package_number',
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('upcoming', 'upcoming'), ('dropped_off', 'dropped_off'), ('ongoing', 'ongoing'), ('arrived', 'arrived'), ('completed', 'completed')], max_length=20),
        ),
    ]
