# Generated by Django 4.2.1 on 2023-06-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_merge_20230613_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='drop_off_zone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='drop_off_zone',
        ),
        migrations.DeleteModel(
            name='DropOffZone',
        ),
    ]
