# Generated by Django 4.2.1 on 2023-06-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_rename_delivery_number_package_package_number_and_more'),
        ('account', '0030_remove_package_drop_off_zone_and_more'),
    ]

    operations = [
    ]
