# Generated by Django 4.2.1 on 2023-06-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_user_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='deliveryType',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('express', 'Express')], max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('dropped_off', 'Dropped Off'), ('ongoing', 'Ongoing'), ('arrived', 'Arrived'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tag',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
