# Generated by Django 4.2.1 on 2023-06-13 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_merge_20230613_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='dropOffLocation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
