# Generated by Django 4.2.1 on 2023-06-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_alter_package_deliverytype_and_more'),
        ('account', '0032_alter_package_dropofflocation'),
    ]

    operations = [
    ]
