# Generated by Django 4.2.1 on 2023-06-14 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_merge_20230613_1138'),
        ('account', '0033_merge_20230613_1541'),
    ]

    operations = [
    ]
