# Generated by Django 4.2.1 on 2023-06-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_merge_20230613_1541'),
        ('account', '0034_merge_20230613_1630'),
    ]

    operations = [
    ]
