# Generated by Django 4.2.1 on 2023-06-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_merge_20230613_1630'),
        ('account', '0034_merge_20230614_0922'),
    ]

    operations = [
    ]
