# Generated by Django 4.2.1 on 2023-06-14 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_merge_20230613_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='dropOffLocation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages_dropped_off', to=settings.AUTH_USER_MODEL),
        ),
    ]
