# Generated by Django 4.2.1 on 2023-06-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_user_address_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='warehouse',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
