# Generated by Django 4.2.1 on 2023-06-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_alter_package_dropofflocation'),
        ('account', '0037_user_warehouse'),
    ]

    operations = [
    ]
