# Generated by Django 4.2.1 on 2023-06-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_merge_20230614_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
