# Generated by Django 4.2.1 on 2023-06-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='deliveryType',
            field=models.CharField(choices=[('standard', 'standard'), ('premium', 'premium'), ('express', 'express')], max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('upcoming', 'upcoming'), ('dropped_off', 'dropped Off'), ('dispatched', 'dispatched'), ('en_route', 'en_route'), ('warehouse_arrival', 'warehouse_arrival'), ('ready_for_pickup', 'ready_for_pickup'), ('ongoing', 'ongoing'), ('arrived', 'arrived'), ('completed', 'completed')], max_length=20),
        ),
    ]
