# Generated by Django 4.2.1 on 2023-06-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_alter_package_deliverytype_alter_package_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('upcoming', 'upcoming'), ('dropped_off', 'dropped Off'), ('dispatched', 'dispatched'), ('en_route', 'en_route'), ('warehouse_arrival', 'warehouse_arrival'), ('in_house', 'in house'), ('ready_for_pickup', 'ready_for_pickup'), ('ongoing', 'ongoing'), ('arrived', 'arrived'), ('completed', 'completed')], max_length=20),
        ),
    ]
