# Generated by Django 4.2.1 on 2023-06-22 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_alter_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages_in_house', to=settings.AUTH_USER_MODEL),
        ),
    ]
